name: tensorflow-example
channels:
  - conda-forge
dependencies:
  - python=3.7
  - pip
  - pip:
    - mlflow==1.27.0
    - tensorflow==2.0.0
    - protobuf==3.19.4
    - boto3
variables:
  MLFLOW_TRACKING_INSECURE_TLS: "true"
  MLFLOW_TRACKING_URI: "<https://<ip>:32222>"
  MLFLOW_TRACKING_TOKEN: "<Token>" 
