name: pytorch-example
channels:
- conda-forge
dependencies:
- python=3.8.2
- pip
- pip:
  - sklearn
  - cloudpickle==1.6.0
  - boto3
  - torchvision>=0.9.1
  - torch>=1.9.0
  - mlflow
variables:
  MLFLOW_TRACKING_INSECURE_TLS: "true"
  MLFLOW_TRACKING_URI: "<https://<ip>:32222>"
  MLFLOW_TRACKING_TOKEN: "<Token>" 